config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :inventories
  devise_for :users
  get 'dashboard/index'
  get '/home' => 'dashboard#index'
  get '/test' => 'dashboard#testrun'
  get '/HIMS' => 'dashboard#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :item
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  belongs_to :inventory
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :inventory
         has_many :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
def after_sign_out_path_for(resource_or_scope)
  request.referrer
end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    before_action :authenticate_user!
    skip_before_action :verify_authenticity_token
  def index
  end
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!
skip_before_action :verify_authenticity_token
  # GET /inventories
  # GET /inventories.json
  def index

    if params[:type] == "name"
      if params[:order] =="des"
        @inventories = Inventory.where(user_id: current_user.id).order(name: :desc)

      else
          @inventories = Inventory.where(user_id: current_user.id).order(:name)

    end
  elsif params[:type] == "quantity"
      if params[:order] =="des"
        @inventories = Inventory.where(user_id: current_user.id).order(total_quantity: :desc)

      else
          @inventories = Inventory.where(user_id: current_user.id).order(:total_quantity)

    end

    elsif params[:type] == "zero"

          @inventories = Inventory.where(user_id: current_user.id).where( total_quantity: 0)

        elsif params[:type] == "others"

          @inventories = Inventory.where(user_id: current_user.id).where( category: "others")

        elsif params[:type] == "drinks"

          @inventories = Inventory.where(user_id: current_user.id).where( category: "drinks")

        elsif params[:type] == "food"

          @inventories = Inventory.where(user_id: current_user.id).where( category: "food")

        elsif params[:type] == "clean"

          @inventories = Inventory.where(user_id: current_user.id).where( category: "clean")

      elsif params[:foo] == "searchName"

      @inventories = Inventory.where("name like ?", "%#{params[:productName]}%")

    else
        @inventories = Inventory.where(user_id: current_user.id)
    end
    puts current_user.email
        respond_to do |format|
      format.json {
          render :json => @inventories,
          include: :user
      }

      format.html
    end
  end

  # GET /inventories/1
  # GET /inventories/1.json
  def show
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit
  end

  # POST /inventories
  # POST /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)
    @inventory.user = current_user
    respond_to do |format|
      if @inventory.save
        format.html { redirect_to @inventory, notice: 'Inventory was successfully created.' }
        format.json { render :show, status: :created, location: @inventory }
      else
        format.html { render :new }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventories/1
  # PATCH/PUT /inventories/1.json
  def update
    puts "I am updating yoyoyoyoyoyoyoyoyoyoyoyoyoyo"
    respond_to do |format|
      if @inventory.update(inventory_params)
        puts "Happy Happy HGappy Happy"
        format.html { redirect_to @inventory, notice: 'Inventory was successfully updated.' }
        format.json { render :show, status: :ok, location: @inventory }
      else
        puts "Failre in update civilisation"
        format.html { render :edit }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1
  # DELETE /inventories/1.json
  def destroy
    @inventory.destroy
    puts params
    respond_to do |format|
      format.html { redirect_to inventories_url, notice: 'Inventory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory
      @inventory = Inventory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inventory_params
      params.require(:inventory).permit(:name, :remarks, :total_quantity, :unsorted_quantity, :sorted_quantity, :image_url, :user_id, :category)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!
skip_before_action :verify_authenticity_token
  # GET /items
  # GET /items.json
  def index
    @items = Item.where(user_id: current_user.id)
    respond_to do |format|
      format.json {
          render :json => @items,
          include: :inventory
      }

      format.html
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    puts "I am creating items"
    @item = Item.new(item_params)
    @item.user = current_user
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:status, :user_id, :inventory_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/dashboard/index.html.erb
<div class="bodyApp">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<link href="https://fonts.googleapis.com/css2?family=Aldrich&display=swap" rel="stylesheet">



<%= javascript_pack_tag 'hello_react' %>

<%= link_to destroy_user_session_path, :method => :delete do%>
  <%= image_tag("/power.png", :class=> "testify") %>
<% end %>

<script type="text/javascript"
        src="https://cdn.jsdelivr.net/npm/emailjs-com@2/dist/email.min.js">
</script>
<script type="text/javascript">
   (function(){
      emailjs.init("user_bFNbGCbL0PuufwmGrNdxx");
   })();
</script>
</div>

app/views/dashboard/testrun.html.erb
<h1> Test Run</h1>

app/views/inventories/_form.html.erb
<%= form_with(model: inventory, local: true) do |form| %>
  <% if inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
        <% inventory.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :remarks %>
    <%= form.text_area :remarks %>
  </div>

  <div class="field">
    <%= form.label :total_quantity %>
    <%= form.number_field :total_quantity %>
  </div>

  <div class="field">
    <%= form.label :unsorted_quantity %>
    <%= form.number_field :unsorted_quantity %>
  </div>

  <div class="field">
    <%= form.label :sorted_quantity %>
    <%= form.number_field :sorted_quantity %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/inventories/edit.html.erb
<h1>Editing Inventory</h1>

<%= render 'form', inventory: @inventory %>

<%= link_to 'Show', @inventory %> |
<%= link_to 'Back', inventories_path %>

app/views/inventories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inventories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Remarks</th>
      <th>Total quantity</th>
      <th>Unsorted quantity</th>
      <th>Sorted quantity</th>
      <th>Image url</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inventories.each do |inventory| %>
      <tr>
        <td><%= inventory.name %></td>
        <td><%= inventory.remarks %></td>
        <td><%= inventory.total_quantity %></td>
        <td><%= inventory.unsorted_quantity %></td>
        <td><%= inventory.sorted_quantity %></td>
        <td><%= inventory.image_url %></td>
        <td><%= inventory.user_id %></td>
        <td><%= link_to 'Show', inventory %></td>
        <td><%= link_to 'Edit', edit_inventory_path(inventory) %></td>
        <td><%= link_to 'Destroy', inventory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inventory', new_inventory_path %>

app/views/inventories/new.html.erb
<h1>New Inventory</h1>

<%= render 'form', inventory: @inventory %>

<%= link_to 'Back', inventories_path %>

app/views/inventories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @inventory.name %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @inventory.remarks %>
</p>

<p>
  <strong>Total quantity:</strong>
  <%= @inventory.total_quantity %>
</p>

<p>
  <strong>Unsorted quantity:</strong>
  <%= @inventory.unsorted_quantity %>
</p>

<p>
  <strong>Sorted quantity:</strong>
  <%= @inventory.sorted_quantity %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @inventory.image_url %>
</p>

<p>
  <strong>User:</strong>
  <%= @inventory.user_id %>
</p>

<%= link_to 'Edit', edit_inventory_path(@inventory) %> |
<%= link_to 'Back', inventories_path %>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :inventory_id %>
    <%= form.text_field :inventory_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>User</th>
      <th>Inventory</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.status %></td>
        <td><%= item.user_id %></td>
        <td><%= item.inventory_id %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @item.status %>
</p>

<p>
  <strong>User:</strong>
  <%= @item.user_id %>
</p>

<p>
  <strong>Inventory:</strong>
  <%= @item.inventory_id %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HIM</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>